import { createPortal } from "react-dom";
import { FoodCard } from "./FoodCard";
import { FoodCardGrid } from "./FoodCardGrid";
import { stageTitle, type BoardSession } from "../game/boardRules";

export function GameModal({ session, seconds, selected, busy, onToggle, onSubmit, onConfirm }: { session: BoardSession; seconds: number; selected: string[]; busy: boolean; onToggle: (foodCode: string) => void; onSubmit: () => void; onConfirm: () => void }) {
  const result = session.phase === "roundResult" || session.phase === "sessionResult";
  return createPortal(<div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/55 p-3"><section className="flex max-h-[88vh] w-[min(92vw,1080px)] flex-col overflow-hidden rounded-[32px] bg-[#fbfaf7] shadow-2xl"><header className="border-b border-black/5 px-6 py-5"><p className="text-xs font-black tracking-[0.16em] text-brand">{session.stage.toUpperCase()}</p><h2 className="mt-1 text-2xl font-black">{session.phase==="study"?`영양정보를 기억하세요 (${seconds})`:stageTitle(session.stage)}</h2></header><div className="min-h-0 flex-1 overflow-y-auto px-6 py-5">{result&&session.feedback?<div className="mx-auto max-w-xl py-8 text-center"><p className="text-3xl font-black">{session.feedback.headline}</p><p className="mt-3 text-neutral-600">{session.feedback.detail}</p><p className="mt-5 text-3xl font-black text-brand">+{session.feedback.points} POINT</p></div>:<FoodCardGrid>{session.foods.map(food=><FoodCard key={food.food_code} food={food} selected={selected.includes(food.food_code)} showNutrition={session.phase==="study"} disabled={session.phase==="study"} onSelect={onToggle}/>)}</FoodCardGrid>}</div><footer className="flex justify-end gap-2 border-t border-black/5 px-6 py-4">{result?<button onClick={onConfirm} className="rounded-full bg-brand px-6 py-3 font-bold text-white">확인</button>:session.phase!=="study"?<button disabled={busy||selected.length===0} onClick={onSubmit} className="rounded-full bg-brand px-6 py-3 font-bold text-white disabled:opacity-40">제출</button>:null}</footer></section></div>,document.body);
}
